#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-03-28 11:39:01      |
#-------------------------------------------------+
# name: bac_circular_fig.pl
# func: draw the circluar figure of Bacteria Genome with COG annotation
# version:: 0.1
# just for the finish Bacteria Genome

use strict;
use warnings;
