#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-06-23 17:28:00      |
#-------------------------------------------------+
# name: meme2karyo.pl
# func: draw meme result, show the motif position 
# version:: 0.1

use strict;
use warnings;



my $infile = shift @ARGV;


&meme2karyo($infile);

sub meme2karyo 
{
	my $file = shift;


}
