shell: /usr/bin/bash
activate: /home/earthtest/miniconda3/bin/activate
deactivate: /home/earthtest/miniconda3/bin/deactivate
rscript: /home/earthtest/miniconda3/envs/R4.1.2/bin/Rscript
python: /home/earthtest/miniconda3/envs/base_env/bin/python
blastn: /home/earthtest/miniconda3/envs/base_env/bin/blastn
java: /home/earthtest/miniconda3/envs/base_env/bin/java
wgsim: /home/earthtest/miniconda3/envs/base_env/bin/wgsim
bwa: /home/earthtest/miniconda3/envs/base_env/bin/bwa
bowtie2: /home/earthtest/miniconda3/envs/base_env/bin/bowtie2
samtools: /home/earthtest/miniconda3/envs/base_env/bin/samtools
fasttree: /home/earthtest/miniconda3/envs/base_env/bin/FastTree
label: /sdbb/share/software/IRMA/IRMA-v0.6.1/LABEL
GDHR: /sdbb/share/lib/GDHR
cgmlst: /sdbb/share/software/WY-cgMLST/v1.0.0
fastp: /home/earthtest/miniconda3/envs/base_env/bin/fastp
parallel: /home/earthtest/miniconda3/envs/denovo/bin/parallel
makeblastdb: /home/earthtest/miniconda3/envs/base_env/bin/makeblastdb
