#软件
python: /home/earthtest/miniconda3/envs/base_env/bin/python
samtools: /home/mengxf/mambaforge/envs/bio/bin/samtools
prokka: /home/lanlei/miniconda3/envs/prokka/bin/prokka
seqkit: /home/earthtest/miniconda3/envs/microbial_wgs/bin/seqkit
parallel: /home/earthtest/miniconda3/envs/microbial_wgs/bin/parallel

#参数
prlnum: 8 #parallel number
threads: 12
