#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2015-04-14 23:06:06      |
#-------------------------------------------------+
# name: band2len.pl
# func: 
# version:: 0.1

use strict;
use warnings;

my %size;
while(<>)
{
	my ($chr,$sta,$end) = (split /\t/)[0,1,2];
	$size{$chr} = $end;
}

my @array = (1 .. 22 , "X", "Y");
@array = map { "chr$_" } @array;

foreach (@array)
{
	print "$_\t$size{$_}\n";
}
